#!/bin/bash

aclocal -I . && \
    autoconf && \
        automake --add-missing --copy

status=$?

if [ $status != 0 ]; then
    echo "Failed to bootstrap."
    exit $status
fi

if [ -n "$1" ]; then
    case $1 in
        noconf*|NOCONF*)
	    exit 0
	    ;;
        *)
            ;;
    esac
fi


if [ -z "$NOCONFIGURE" ]; then
    ./configure $*
fi
